apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-web-deployment
  labels:
    app: mlops-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-web
  template:
    metadata:
      labels:
        app: mlops-web
    spec:
      containers:
      - name: mlops-web
        image: gcr.io/tu-project-id/mlops-web:latest # <--- RUTA DE IMAGEN
        ports:
        - containerPort: 8501
        env:
        - name: API_URL
          value: http://mlops-api-service:5000/predict # <--- Conexión al servicio interno de la API

