name: MLOps with CML
on: [push, pull_request]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: DVC and Python setup
        uses: iterative/setup-dvc@v1
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Configure Git
        run: |
          git config --global user.email "alex.m.guinea@gmail.com"
          git config --global user.name "xAlexMGGx"
      - name: Restore DVC Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/dvc
          key: dvc-cache-${{ hashFiles('dvc.yaml', 'dvc.lock') }}
          restore-keys: |
            dvc-cache-
      - name: DVC Pull
        env:
          DAGSHUB_API_KEY: ${{ secrets.DAGSHUB_API_KEY }}
        # Las credenciales de Dagshub son necesarias para acceder al almacenamiento remoto
        run: |
          dvc remote modify origin --local access_key_id $DAGSHUB_API_KEY
          dvc remote modify origin --local secret_access_key $DAGSHUB_API_KEY
          dvc pull -r origin
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pyyaml
          pip install -r requirements.txt
      - name: Install CML manually
        run: |
          npm install -g @dvcorg/cml
      - name: Run training script
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_API_KEY }}
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        run: |
          dvc repro
  deploy-to-gke:
    needs: train-and-report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: DVC and Python setup
        uses: iterative/setup-dvc@v1
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: Set up gcloud CLI and kubectl
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: 'latest'
          install_components: 'gke-gcloud-auth-plugin'
      - name: Get GKE credentials
        run: gcloud container clusters get-credentials ${{ vars.GKE_CLUSTER }} --zone ${{ vars.GKE_ZONE }} --project ${{ vars.GCP_PROJECT_ID }}
      - name: DVC Pull
        env:
          DAGSHUB_API_KEY: ${{ secrets.DAGSHUB_API_KEY }}
        # Las credenciales de Dagshub son necesarias para acceder al almacenamiento remoto
        run: |
          dvc remote modify origin --local access_key_id $DAGSHUB_API_KEY
          dvc remote modify origin --local secret_access_key $DAGSHUB_API_KEY
          dvc pull -r origin
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Configure Docker to use GCR
        run: gcloud auth configure-docker
      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/${{ vars.GCP_PROJECT_ID }}/mlops-api:latest .
          docker push gcr.io/${{ vars.GCP_PROJECT_ID }}/mlops-api:latest
      - name: Deploy to GKE
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml